apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/poker
  - poker-imageautomation.yaml
  - poker-imagepolicy.yaml
  - poker-imagerepository.yaml
patchesStrategicMerge:
  - poker-values.yaml
