apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/poker
  - poker-imageautomation.yaml
  - poker-imagepolicy.yaml
  - routing
patchesStrategicMerge:
  - poker-helm-release.yaml
patchesStrategicMerge:
  - poker-helm-release-canary.yaml

