apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-9318d4ee-20220524102210 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
