apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-c12b61a2-20220525160926 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
