apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-8ff73242-20220525150049 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
