apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-2768eb88-20220525101232 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
