apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-f0e2f238-20220523133413 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 3
