apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-205c8cc5-20220526110157 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
