apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-f2524f2b-20220525145430 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
