apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-fd93e42d-20220524111647 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
