apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-04b61f34-20220524110636 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
