apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:1.0.10 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 3