apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-d3c52406-20220523113229 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 3
