apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-dd5d533f-20220525090705 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
