apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-2d053254-20220525090739 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
