apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-59d9919d-20220525091821 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
