apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-b898142c-20220524140324 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
