apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-dadc0991-20220530090142 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
