apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-9fda736f-20220526143708 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
