apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-dfbe2a52-20220525155825 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
