apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
  namespace: formidable
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-ce259bcd-20220615152157 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
    podLabels:
      version: v1
