apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-18e0c1f8-20220524085857 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
