apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-05e2301d-20220525161037 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
