apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-bfefc1d3-20220524104615 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
