apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-9688c0b7-20220524141302 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
