apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: poker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: poker
  filterTags:
    pattern: '^development-[a-fA-F0-9]+-*'
  policy:
     numerical:
      order: asc

# apiVersion: image.toolkit.fluxcd.io/v1beta1
# kind: ImagePolicy
# metadata:
#   name: poker
#   namespace: flux-system
# spec:
#   imageRepositoryRef:
#     name: poker
#   filterTags:
#     pattern: '^development-[a-fA-F0-9]+-\d{4}-\d{2}-\d{2}T\d{6}Z'
#     extract: '$ts'
#   policy:
#      numerical:
#       order: asc