apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-a55d4c4e-22222222222222 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 3
