apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-65fe0c05-20220520174908 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 3
