apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-a6f4ee77-20220524134943 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
