apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-bb80ef2a-20220525151837 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
