apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-8b10222e-20220525093559 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
