apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
  namespace: formidable
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-5873b2b7-20220616095422 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
    podLabels:
      version: v1
