apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-20cea361-20220526095525 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
