apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-9676f107-20222005093806 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
