apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-013a89ed-20220525094452 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
