apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-30d92d97-20220527101742 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
