apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-c5c18a67-20220524101138 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
