apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  values:
    image: docker.io/seanmcguigan/poker:development-1bd7cfc3-20220525091623 # {"$imagepolicy": "flux-system:poker"}
    replicaCount: 1
