apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  releaseName: poker
  chart:
    spec:
      chart: poker
      sourceRef:
        kind: HelmRepository
        name: seanmcguigan-helmrepo
        namespace: flux-system
      version: "1.0.7"
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort