apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: poker
spec:
  releaseName: poker
  chart:
    spec:
      chart: poker
      sourceRef:
        kind: HelmRepository
        name: seanmcguigan-helmrepo
        namespace: flux-system
      version: "0.1.4"
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    image:  docker.io/seanmcguigan/poker:1.0.8 # {"$imagepolicy": "flux-system:poker"}
    service:
      type: ClusterIP
