apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker
  namespace: formidable
spec:
  selector:
    matchLabels:
      app: poker
  template:
    metadata:
      labels:
        app: poker
    spec:
      containers:
        - name: poker
          image: docker.io/seanmcguigan/poker:dev-0teeky
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP