apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 10m # The interval defines at which interval the Helm repository contents are fetched
  url: https://kiali.org/helm-charts
