apiVersion: apps/v1
kind: Deployment
metadata:
  name: poker
  namespace: formidable
spec:
  selector:
    matchLabels:
      app: poker
  template:
    metadata:
      labels:
        app: poker
    spec:
      containers:
      - name: poker
        image: ghcr.io/stefanprodan/podinfo:5.0.3 # {"$imagepolicy": "flux-system:podinfo"}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
