apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  dependsOn:
    - name: istio-base
    - name: istiod
  releaseName: istio-ingress
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.13.4"
  interval: 1m
  install:
    remediation:
      retries: 3
  values:
    service:
      # Type of service. Set to "None" to disable the service entirely
      type: NodePort
