apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.13.4"
  interval: 1m
  install:
    crds: Create
    remediation:
      retries: 3
