apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
spec:
  releaseName: apache
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "9.0.17"
  interval: 1m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/apache/values.yaml
  values:
    service:
      type: NodePort
      
